site_name: BayBE
site_url: https://emdgroup.github.io/baybe/
repo_url: https://github.com/emdgroup/baybe/
copyright: Copyright &copy; 2022-2025 Merck KGaA, Darmstadt, Germany
theme:
  name: material
  logo: assets/favicon.ico
  palette:
    scheme: slate
    primary: custom
    accent: custom
  features:
    - navigation.instant
    - navigation.tabs
    - navigation.tabs.sticky
    - navigation.top
    - navigation.tracking

extra_css:
  - stylesheets/extra.css

nav:
  - Readme: README.md
  - Concepts:
    - Serialization: userguide/serialization.md
  - Misc:
    - Contributors: CONTRIBUTORS.md
  - API Reference: reference/

markdown_extensions:
  - admonition
  - attr_list
  - md_in_html
  - pymdownx.details
  - pymdownx.emoji:
      emoji_index: !!python/name:material.extensions.emoji.twemoji
      emoji_generator: !!python/name:material.extensions.emoji.to_svg
  - pymdownx.extra
  - pymdownx.superfences
  - toc:
      permalink: "#"

plugins:
- search  
- section-index
- autorefs:
    resolve_closest: true
- api-autonav:
    modules: [baybe]
- mkdocstrings:
    handlers:
      python:
        options:
          docstring_section_style: table # or "list"
          heading_level: 1
          merge_init_into_class: true
          parameter_headings: true
          separate_signature: true
          show_root_heading: true
          show_signature_annotations: true
          show_symbol_type_heading: true
          show_symbol_type_toc: true
          inherited_members: false  # default is false
          summary: true
          extensions:
          - griffe_fieldz:
              add_fields_to: docstring-parameters
              remove_fields_from_members: true
        import:
        - https://pandas.pydata.org/docs/objects.inv

extra:
  toc:
    disable:
      - README.md
  navigation:
    disable:
      - README.md